# Generated by Django 5.0.6 on 2024-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('nombres_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('apellidos_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('correo_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('rut_str', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('direccion_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('fechanacimiento_dat', models.DateField(blank=True, db_column='fechaNacimiento_dat', null=True)),
                ('fecharegistro_dat', models.DateField(blank=True, db_column='fechaRegistro_dat', null=True)),
                ('fechamodificacion_dat', models.DateField(blank=True, db_column='fechaModificacion_dat', null=True)),
                ('usuariomodificacion_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='usuarioModificacion_str', max_length=30, null=True)),
                ('motivomodificacion_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='motivoModificacion_str', max_length=50, null=True)),
            ],
            options={
                'db_table': 'apoderado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoapoderado',
            fields=[
                ('idtipoapoderado_int', models.AutoField(db_column='idTipoApoderado_int', primary_key=True, serialize=False)),
                ('nombre_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipoApoderado',
                'managed': False,
            },
        ),
    ]
