# Generated by Django 5.0.6 on 2024-06-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0003_tiporol_usuario_delete_tiporolusuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
    ]
