# Generated by Django 5.0.6 on 2024-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('fecharegistro_dat', models.DateField(blank=True, db_column='fechaRegistro_dat', null=True)),
                ('fechamodificacion_dat', models.DateField(blank=True, db_column='fechaModificacion_dat', null=True)),
                ('usuariomoficicacion_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='usuarioMoficicacion_str', max_length=20, null=True)),
                ('motivomodificacion_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='motivoModificacion_str', max_length=100, null=True)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoasignatura',
            fields=[
                ('idtipoasignatura_int', models.AutoField(db_column='idTipoAsignatura_int', primary_key=True, serialize=False)),
                ('nombre_str', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'tipoAsignatura',
                'managed': False,
            },
        ),
    ]
