# Generated by Django 5.0.6 on 2024-06-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appestudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={},
        ),
    ]
