# Generated by Django 5.0.6 on 2024-06-13 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapoderados', '0001_initial'),
        ('appcomunes', '0001_initial'),
        ('appestudiantes', '0002_alter_estudiante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='idbeca_int',
            field=models.ForeignKey(blank=True, db_column='idBeca_int', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appcomunes.beca'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='idcomuna_int',
            field=models.ForeignKey(blank=True, db_column='idComuna_int', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appcomunes.comuna'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='idnacionalidad_int',
            field=models.ForeignKey(blank=True, db_column='idNacionalidad_int', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appcomunes.pais'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='idnivelsocioeconomico_int',
            field=models.ForeignKey(blank=True, db_column='idNivelSocioEconomico_int', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appcomunes.nivelsocioeconomico'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='idregion_int',
            field=models.ForeignKey(blank=True, db_column='idRegion_int', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appcomunes.region'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rutapoderado_str',
            field=models.ForeignKey(blank=True, db_column='rutApoderado_str', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appapoderados.apoderado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telcontacto_str',
            field=models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='telContacto_str', max_length=20, null=True),
        ),
    ]
