# Generated by Django 5.0.6 on 2024-06-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appestudiantes', '0003_estudiante_idbeca_int_estudiante_idcomuna_int_and_more'),
    ]

    operations = [
    ]
