# Generated by Django 5.0.6 on 2024-06-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appestudiantes', '0004_synchronize_estudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False},
        ),
    ]
